//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Existing keys
        public static string User {
            get { return ResourceManager.GetString("User", resourceCulture); }
        }
        
        public static string Dashboard {
            get { return ResourceManager.GetString("Dashboard", resourceCulture); }
        }
        
        public static string Bookings {
            get { return ResourceManager.GetString("Bookings", resourceCulture); }
        }
        
        public static string Maintenance {
            get { return ResourceManager.GetString("Maintenance", resourceCulture); }
        }
        
        public static string Settings {
            get { return ResourceManager.GetString("Settings", resourceCulture); }
        }
        
        public static string Aircraft {
            get { return ResourceManager.GetString("Aircraft", resourceCulture); }
        }
        
        public static string HomeTitle {
            get { return ResourceManager.GetString("Home", resourceCulture); }
        }

        // Navigation & Layout
        public static string Login {
            get { return ResourceManager.GetString("Login", resourceCulture); }
        }
        
        public static string Logout {
            get { return ResourceManager.GetString("Logout", resourceCulture); }
        }
        
        public static string Register {
            get { return ResourceManager.GetString("Register", resourceCulture); }
        }
        
        public static string Hello {
            get { return ResourceManager.GetString("Hello", resourceCulture); }
        }
        
        public static string Privacy {
            get { return ResourceManager.GetString("Privacy", resourceCulture); }
        }
        
        public static string FindAircraft {
            get { return ResourceManager.GetString("FindAircraft", resourceCulture); }
        }
        
        public static string MyBookings {
            get { return ResourceManager.GetString("MyBookings", resourceCulture); }
        }
        
        public static string MyProfile {
            get { return ResourceManager.GetString("MyProfile", resourceCulture); }
        }
        
        public static string CreateCompany {
            get { return ResourceManager.GetString("CreateCompany", resourceCulture); }
        }
        
        public static string AdminPanel {
            get { return ResourceManager.GetString("AdminPanel", resourceCulture); }
        }
        
        public static string SystemDashboard {
            get { return ResourceManager.GetString("SystemDashboard", resourceCulture); }
        }
        
        public static string Users {
            get { return ResourceManager.GetString("Users", resourceCulture); }
        }
        
        public static string Tenants {
            get { return ResourceManager.GetString("Tenants", resourceCulture); }
        }
        
        public static string ContactMaintenance {
            get { return ResourceManager.GetString("ContactMaintenance", resourceCulture); }
        }
        
        public static string SignIn {
            get { return ResourceManager.GetString("SignIn", resourceCulture); }
        }

        // CompanyOwner Dashboard
        public static string WelcomeBack {
            get { return ResourceManager.GetString("WelcomeBack", resourceCulture); }
        }
        
        public static string TotalAircraft {
            get { return ResourceManager.GetString("TotalAircraft", resourceCulture); }
        }
        
        public static string ViewAllAircraft {
            get { return ResourceManager.GetString("ViewAllAircraft", resourceCulture); }
        }
        
        public static string Available {
            get { return ResourceManager.GetString("Available", resourceCulture); }
        }
        
        public static string Unavailable {
            get { return ResourceManager.GetString("Unavailable", resourceCulture); }
        }
        
        public static string PendingApproval {
            get { return ResourceManager.GetString("PendingApproval", resourceCulture); }
        }
        
        public static string ReviewPending {
            get { return ResourceManager.GetString("ReviewPending", resourceCulture); }
        }
        
        public static string MonthlyRevenue {
            get { return ResourceManager.GetString("MonthlyRevenue", resourceCulture); }
        }
        
        public static string ThisMonth {
            get { return ResourceManager.GetString("ThisMonth", resourceCulture); }
        }
        
        public static string BookingOverview {
            get { return ResourceManager.GetString("BookingOverview", resourceCulture); }
        }
        
        public static string TotalBookings {
            get { return ResourceManager.GetString("TotalBookings", resourceCulture); }
        }
        
        public static string Active {
            get { return ResourceManager.GetString("Active", resourceCulture); }
        }
        
        public static string Pending {
            get { return ResourceManager.GetString("Pending", resourceCulture); }
        }
        
        public static string Completed {
            get { return ResourceManager.GetString("Completed", resourceCulture); }
        }
        
        public static string QuickActions {
            get { return ResourceManager.GetString("QuickActions", resourceCulture); }
        }
        
        public static string AddAircraft {
            get { return ResourceManager.GetString("AddAircraft", resourceCulture); }
        }
        
        public static string ManageBookings {
            get { return ResourceManager.GetString("ManageBookings", resourceCulture); }
        }
        
        public static string PendingApprovals {
            get { return ResourceManager.GetString("PendingApprovals", resourceCulture); }
        }
        
        public static string ViewAll {
            get { return ResourceManager.GetString("ViewAll", resourceCulture); }
        }
        
        public static string RecentAircraft {
            get { return ResourceManager.GetString("RecentAircraft", resourceCulture); }
        }
        
        public static string RecentBookings {
            get { return ResourceManager.GetString("RecentBookings", resourceCulture); }
        }
        
        public static string NoBookingsYet {
            get { return ResourceManager.GetString("NoBookingsYet", resourceCulture); }
        }
        
        public static string NoPendingBookings {
            get { return ResourceManager.GetString("NoPendingBookings", resourceCulture); }
        }
        
        public static string NoAircraftYet {
            get { return ResourceManager.GetString("NoAircraftYet", resourceCulture); }
        }
        
        public static string AddFirstAircraft {
            get { return ResourceManager.GetString("AddFirstAircraft", resourceCulture); }
        }
        
        public static string Approve {
            get { return ResourceManager.GetString("Approve", resourceCulture); }
        }
        
        public static string Reject {
            get { return ResourceManager.GetString("Reject", resourceCulture); }
        }
        
        public static string RejectBooking {
            get { return ResourceManager.GetString("RejectBooking", resourceCulture); }
        }
        
        public static string RejectionReason {
            get { return ResourceManager.GetString("RejectionReason", resourceCulture); }
        }
        
        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }
        
        public static string SaveChanges {
            get { return ResourceManager.GetString("SaveChanges", resourceCulture); }
        }
        
        public static string Pilot {
            get { return ResourceManager.GetString("Pilot", resourceCulture); }
        }
        
        public static string Dates {
            get { return ResourceManager.GetString("Dates", resourceCulture); }
        }
        
        public static string Amount {
            get { return ResourceManager.GetString("Amount", resourceCulture); }
        }
        
        public static string Status {
            get { return ResourceManager.GetString("Status", resourceCulture); }
        }

        // CompanyOwner Settings
        public static string CompanySettings {
            get { return ResourceManager.GetString("CompanySettings", resourceCulture); }
        }
        
        public static string ManageCompanyProfile {
            get { return ResourceManager.GetString("ManageCompanyProfile", resourceCulture); }
        }
        
        public static string CompanyProfile {
            get { return ResourceManager.GetString("CompanyProfile", resourceCulture); }
        }
        
        public static string UsageLimits {
            get { return ResourceManager.GetString("UsageLimits", resourceCulture); }
        }
        
        public static string MonthlyBookings {
            get { return ResourceManager.GetString("MonthlyBookings", resourceCulture); }
        }

        // SystemAdmin Dashboard
        public static string SystemAdminDashboard {
            get { return ResourceManager.GetString("SystemAdminDashboard", resourceCulture); }
        }
        
        public static string SystemOverview {
            get { return ResourceManager.GetString("SystemOverview", resourceCulture); }
        }
        
        public static string SystemAdmin {
            get { return ResourceManager.GetString("SystemAdmin", resourceCulture); }
        }
        
        public static string TotalUsers {
            get { return ResourceManager.GetString("TotalUsers", resourceCulture); }
        }
        
        public static string ManageUsers {
            get { return ResourceManager.GetString("ManageUsers", resourceCulture); }
        }
        
        public static string ActiveTenants {
            get { return ResourceManager.GetString("ActiveTenants", resourceCulture); }
        }
        
        public static string ManageTenants {
            get { return ResourceManager.GetString("ManageTenants", resourceCulture); }
        }
        
        public static string AcrossAllTenants {
            get { return ResourceManager.GetString("AcrossAllTenants", resourceCulture); }
        }
        
        public static string RegisteredInSystem {
            get { return ResourceManager.GetString("RegisteredInSystem", resourceCulture); }
        }
        
        public static string TopTenantsByBookings {
            get { return ResourceManager.GetString("TopTenantsByBookings", resourceCulture); }
        }
        
        public static string ViewAllTenants {
            get { return ResourceManager.GetString("ViewAllTenants", resourceCulture); }
        }
        
        public static string Inactive {
            get { return ResourceManager.GetString("Inactive", resourceCulture); }
        }
        
        public static string NoTenantsYet {
            get { return ResourceManager.GetString("NoTenantsYet", resourceCulture); }
        }

        // SystemAdmin Tenants
        public static string AllTenants {
            get { return ResourceManager.GetString("AllTenants", resourceCulture); }
        }
        
        public static string InactiveTenants {
            get { return ResourceManager.GetString("InactiveTenants", resourceCulture); }
        }
        
        public static string Created {
            get { return ResourceManager.GetString("Created", resourceCulture); }
        }
        
        public static string Actions {
            get { return ResourceManager.GetString("Actions", resourceCulture); }
        }
        
        public static string Activate {
            get { return ResourceManager.GetString("Activate", resourceCulture); }
        }
        
        public static string Deactivate {
            get { return ResourceManager.GetString("Deactivate", resourceCulture); }
        }
        
        public static string BackToDashboard {
            get { return ResourceManager.GetString("BackToDashboard", resourceCulture); }
        }
        
        public static string NoTenantsFound {
            get { return ResourceManager.GetString("NoTenantsFound", resourceCulture); }
        }
        
        public static string DeactivateWarning {
            get { return ResourceManager.GetString("DeactivateWarning", resourceCulture); }
        }
        
        public static string ActivateInfo {
            get { return ResourceManager.GetString("ActivateInfo", resourceCulture); }
        }
        
        public static string Tenant {
            get { return ResourceManager.GetString("Tenant", resourceCulture); }
        }
        
        public static string Slug {
            get { return ResourceManager.GetString("Slug", resourceCulture); }
        }

        // Home/Index page
        public static string AircraftSaaSPortal {
            get { return ResourceManager.GetString("AircraftSaaSPortal", resourceCulture); }
        }
        
        public static string HeroDescription {
            get { return ResourceManager.GetString("HeroDescription", resourceCulture); }
        }
        
        public static string BrowseAircraft {
            get { return ResourceManager.GetString("BrowseAircraft", resourceCulture); }
        }
        
        public static string SearchFilterDescription {
            get { return ResourceManager.GetString("SearchFilterDescription", resourceCulture); }
        }
        
        public static string SearchAvailableAircraft {
            get { return ResourceManager.GetString("SearchAvailableAircraft", resourceCulture); }
        }
        
        public static string BookAircraftForFlights {
            get { return ResourceManager.GetString("BookAircraftForFlights", resourceCulture); }
        }
        
        public static string ManageYourBookings {
            get { return ResourceManager.GetString("ManageYourBookings", resourceCulture); }
        }
        
        public static string SignInToBrowse {
            get { return ResourceManager.GetString("SignInToBrowse", resourceCulture); }
        }
        
        public static string CompanyDashboard {
            get { return ResourceManager.GetString("CompanyDashboard", resourceCulture); }
        }
        
        public static string CompanyDashboardDescription {
            get { return ResourceManager.GetString("CompanyDashboardDescription", resourceCulture); }
        }
        
        public static string CompanyFleetManagement {
            get { return ResourceManager.GetString("CompanyFleetManagement", resourceCulture); }
        }
        
        public static string ApproveRejectBookings {
            get { return ResourceManager.GetString("ApproveRejectBookings", resourceCulture); }
        }
        
        public static string MaintenanceTracking {
            get { return ResourceManager.GetString("MaintenanceTracking", resourceCulture); }
        }
        
        public static string SignInAsOwner {
            get { return ResourceManager.GetString("SignInAsOwner", resourceCulture); }
        }
        
        public static string NewToPlatform {
            get { return ResourceManager.GetString("NewToPlatform", resourceCulture); }
        }
        
        public static string NewToPlatformDescription {
            get { return ResourceManager.GetString("NewToPlatformDescription", resourceCulture); }
        }
        
        public static string FreeToRegister {
            get { return ResourceManager.GetString("FreeToRegister", resourceCulture); }
        }
        
        public static string JoinOrCreateCompany {
            get { return ResourceManager.GetString("JoinOrCreateCompany", resourceCulture); }
        }
        
        public static string StartFlyingToday {
            get { return ResourceManager.GetString("StartFlyingToday", resourceCulture); }
        }
        
        public static string CreateAccount {
            get { return ResourceManager.GetString("CreateAccount", resourceCulture); }
        }
        
        public static string QuickAccess {
            get { return ResourceManager.GetString("QuickAccess", resourceCulture); }
        }
        
        public static string BrowseFleet {
            get { return ResourceManager.GetString("BrowseFleet", resourceCulture); }
        }
        
        public static string BrowseFleetDescription {
            get { return ResourceManager.GetString("BrowseFleetDescription", resourceCulture); }
        }
        
        public static string ViewBookings {
            get { return ResourceManager.GetString("ViewBookings", resourceCulture); }
        }
        
        public static string ViewBookingsDescription {
            get { return ResourceManager.GetString("ViewBookingsDescription", resourceCulture); }
        }
        
        public static string ViewProfile {
            get { return ResourceManager.GetString("ViewProfile", resourceCulture); }
        }
        
        public static string ViewProfileDescription {
            get { return ResourceManager.GetString("ViewProfileDescription", resourceCulture); }
        }
        
        public static string FleetManagement {
            get { return ResourceManager.GetString("FleetManagement", resourceCulture); }
        }
        
        public static string FleetManagementDescription {
            get { return ResourceManager.GetString("FleetManagementDescription", resourceCulture); }
        }
        
        public static string ManageFleet {
            get { return ResourceManager.GetString("ManageFleet", resourceCulture); }
        }
        
        public static string GoToDashboard {
            get { return ResourceManager.GetString("GoToDashboard", resourceCulture); }
        }
        
        public static string DashboardDescription {
            get { return ResourceManager.GetString("DashboardDescription", resourceCulture); }
        }
        
        public static string BookingsCardDescription {
            get { return ResourceManager.GetString("BookingsCardDescription", resourceCulture); }
        }
        
        public static string CompanyOwner {
            get { return ResourceManager.GetString("CompanyOwner", resourceCulture); }
        }
        
        public static string ConfirmAction {
            get { return ResourceManager.GetString("ConfirmAction", resourceCulture); }
        }
        
        public static string PleaseProvideReason {
            get { return ResourceManager.GetString("PleaseProvideReason", resourceCulture); }
        }
        
        public static string Availability {
            get { return ResourceManager.GetString("Availability", resourceCulture); }
        }

        // User/Index - Aircraft Catalog
        public static string AircraftCatalog {
            get { return ResourceManager.GetString("AircraftCatalog", resourceCulture); }
        }
        
        public static string FindAndBookDescription {
            get { return ResourceManager.GetString("FindAndBookDescription", resourceCulture); }
        }
        
        public static string SearchFilters {
            get { return ResourceManager.GetString("SearchFilters", resourceCulture); }
        }
        
        public static string Make {
            get { return ResourceManager.GetString("Make", resourceCulture); }
        }
        
        public static string Model {
            get { return ResourceManager.GetString("Model", resourceCulture); }
        }
        
        public static string Category {
            get { return ResourceManager.GetString("Category", resourceCulture); }
        }
        
        public static string AllCategories {
            get { return ResourceManager.GetString("AllCategories", resourceCulture); }
        }
        
        public static string Location {
            get { return ResourceManager.GetString("Location", resourceCulture); }
        }
        
        public static string AirportCode {
            get { return ResourceManager.GetString("AirportCode", resourceCulture); }
        }
        
        public static string MaxHourlyRate {
            get { return ResourceManager.GetString("MaxHourlyRate", resourceCulture); }
        }
        
        public static string StartDate {
            get { return ResourceManager.GetString("StartDate", resourceCulture); }
        }
        
        public static string EndDate {
            get { return ResourceManager.GetString("EndDate", resourceCulture); }
        }
        
        public static string Search {
            get { return ResourceManager.GetString("Search", resourceCulture); }
        }
        
        public static string ClearFilters {
            get { return ResourceManager.GetString("ClearFilters", resourceCulture); }
        }
        
        public static string ShowingAircraft {
            get { return ResourceManager.GetString("ShowingAircraft", resourceCulture); }
        }
        
        public static string AircraftPlural {
            get { return ResourceManager.GetString("AircraftPlural", resourceCulture); }
        }
        
        public static string Hours {
            get { return ResourceManager.GetString("Hours", resourceCulture); }
        }
        
        public static string PerHour {
            get { return ResourceManager.GetString("PerHour", resourceCulture); }
        }
        
        public static string ViewDetails {
            get { return ResourceManager.GetString("ViewDetails", resourceCulture); }
        }
        
        public static string NoAircraftFound {
            get { return ResourceManager.GetString("NoAircraftFound", resourceCulture); }
        }
        
        public static string TryAdjustingFilters {
            get { return ResourceManager.GetString("TryAdjustingFilters", resourceCulture); }
        }
        
        public static string Reviews {
            get { return ResourceManager.GetString("Reviews", resourceCulture); }
        }
        
        public static string ReviewsLower {
            get { return ResourceManager.GetString("ReviewsLower", resourceCulture); }
        }

        // User/MyBookings
        public static string ManageFlightBookings {
            get { return ResourceManager.GetString("ManageFlightBookings", resourceCulture); }
        }
        
        public static string AllBookings {
            get { return ResourceManager.GetString("AllBookings", resourceCulture); }
        }
        
        public static string Cancelled {
            get { return ResourceManager.GetString("Cancelled", resourceCulture); }
        }
        
        public static string CancelBooking {
            get { return ResourceManager.GetString("CancelBooking", resourceCulture); }
        }
        
        public static string ConfirmCancelBooking {
            get { return ResourceManager.GetString("ConfirmCancelBooking", resourceCulture); }
        }
        
        public static string KeepBooking {
            get { return ResourceManager.GetString("KeepBooking", resourceCulture); }
        }

        // User/Profile
        public static string AccountInfoDescription {
            get { return ResourceManager.GetString("AccountInfoDescription", resourceCulture); }
        }
        
        public static string UserInformation {
            get { return ResourceManager.GetString("UserInformation", resourceCulture); }
        }
        
        public static string Email {
            get { return ResourceManager.GetString("Email", resourceCulture); }
        }
        
        public static string Phone {
            get { return ResourceManager.GetString("Phone", resourceCulture); }
        }
        
        public static string LicenseLabel {
            get { return ResourceManager.GetString("LicenseLabel", resourceCulture); }
        }
        
        public static string Expires {
            get { return ResourceManager.GetString("Expires", resourceCulture); }
        }
        
        public static string BookingStatistics {
            get { return ResourceManager.GetString("BookingStatistics", resourceCulture); }
        }
        
        public static string PendingCancelled {
            get { return ResourceManager.GetString("PendingCancelled", resourceCulture); }
        }
        
        public static string ViewMyBookings {
            get { return ResourceManager.GetString("ViewMyBookings", resourceCulture); }
        }

        // User/AircraftDetails
        public static string NotAvailable {
            get { return ResourceManager.GetString("NotAvailable", resourceCulture); }
        }
        
        public static string Year {
            get { return ResourceManager.GetString("Year", resourceCulture); }
        }
        
        public static string TotalAirspeedHours {
            get { return ResourceManager.GetString("TotalAirspeedHours", resourceCulture); }
        }
        
        public static string HourlyRate {
            get { return ResourceManager.GetString("HourlyRate", resourceCulture); }
        }
        
        public static string BaseAirport {
            get { return ResourceManager.GetString("BaseAirport", resourceCulture); }
        }
        
        public static string Company {
            get { return ResourceManager.GetString("Company", resourceCulture); }
        }
        
        public static string NoReviewsYet {
            get { return ResourceManager.GetString("NoReviewsYet", resourceCulture); }
        }
        
        public static string BookThisAircraft {
            get { return ResourceManager.GetString("BookThisAircraft", resourceCulture); }
        }
        
        public static string ReadyForBooking {
            get { return ResourceManager.GetString("ReadyForBooking", resourceCulture); }
        }
        
        public static string SignInToBook {
            get { return ResourceManager.GetString("SignInToBook", resourceCulture); }
        }
        
        public static string UnavailableDescription {
            get { return ResourceManager.GetString("UnavailableDescription", resourceCulture); }
        }

        // User/Book
        public static string Book {
            get { return ResourceManager.GetString("Book", resourceCulture); }
        }
        
        public static string NotAvailableAlert {
            get { return ResourceManager.GetString("NotAvailableAlert", resourceCulture); }
        }
        
        public static string NotAvailableForDates {
            get { return ResourceManager.GetString("NotAvailableForDates", resourceCulture); }
        }
        
        public static string NextAvailable {
            get { return ResourceManager.GetString("NextAvailable", resourceCulture); }
        }
        
        public static string StartDateTime {
            get { return ResourceManager.GetString("StartDateTime", resourceCulture); }
        }
        
        public static string EndDateTime {
            get { return ResourceManager.GetString("EndDateTime", resourceCulture); }
        }
        
        public static string PurposeOfFlight {
            get { return ResourceManager.GetString("PurposeOfFlight", resourceCulture); }
        }
        
        public static string EnterPurpose {
            get { return ResourceManager.GetString("EnterPurpose", resourceCulture); }
        }
        
        public static string EstimatedPrice {
            get { return ResourceManager.GetString("EstimatedPrice", resourceCulture); }
        }
        
        public static string SubmitBookingRequest {
            get { return ResourceManager.GetString("SubmitBookingRequest", resourceCulture); }
        }
        
        public static string AircraftDetails {
            get { return ResourceManager.GetString("AircraftDetails", resourceCulture); }
        }
        
        public static string Registration {
            get { return ResourceManager.GetString("Registration", resourceCulture); }
        }
        
        public static string Base {
            get { return ResourceManager.GetString("Base", resourceCulture); }
        }
        
        public static string BookingInfo {
            get { return ResourceManager.GetString("BookingInfo", resourceCulture); }
        }
        
        public static string BookingSubjectToApproval {
            get { return ResourceManager.GetString("BookingSubjectToApproval", resourceCulture); }
        }
        
        public static string PaymentAfterApproval {
            get { return ResourceManager.GetString("PaymentAfterApproval", resourceCulture); }
        }
        
        public static string PriceCalculatedPerHour {
            get { return ResourceManager.GetString("PriceCalculatedPerHour", resourceCulture); }
        }

        // User/BookingDetails
        public static string BookingDetails {
            get { return ResourceManager.GetString("BookingDetails", resourceCulture); }
        }
        
        public static string TotalAmount {
            get { return ResourceManager.GetString("TotalAmount", resourceCulture); }
        }
        
        public static string Duration {
            get { return ResourceManager.GetString("Duration", resourceCulture); }
        }
        
        public static string PayNow {
            get { return ResourceManager.GetString("PayNow", resourceCulture); }
        }
        
        public static string LeaveReview {
            get { return ResourceManager.GetString("LeaveReview", resourceCulture); }
        }
        
        public static string BackToMyBookings {
            get { return ResourceManager.GetString("BackToMyBookings", resourceCulture); }
        }
        
        public static string YourReview {
            get { return ResourceManager.GetString("YourReview", resourceCulture); }
        }
        
        public static string Verified {
            get { return ResourceManager.GetString("Verified", resourceCulture); }
        }
        
        public static string Excellent {
            get { return ResourceManager.GetString("Excellent", resourceCulture); }
        }
        
        public static string VeryGood {
            get { return ResourceManager.GetString("VeryGood", resourceCulture); }
        }
        
        public static string Good {
            get { return ResourceManager.GetString("Good", resourceCulture); }
        }
        
        public static string Fair {
            get { return ResourceManager.GetString("Fair", resourceCulture); }
        }
        
        public static string Poor {
            get { return ResourceManager.GetString("Poor", resourceCulture); }
        }
        
        public static string ReviewedOn {
            get { return ResourceManager.GetString("ReviewedOn", resourceCulture); }
        }
        
        public static string EditReview {
            get { return ResourceManager.GetString("EditReview", resourceCulture); }
        }
        
        public static string AvailableActions {
            get { return ResourceManager.GetString("AvailableActions", resourceCulture); }
        }
        
        public static string CancelThisBooking {
            get { return ResourceManager.GetString("CancelThisBooking", resourceCulture); }
        }
        
        public static string CancellationNotAvailable {
            get { return ResourceManager.GetString("CancellationNotAvailable", resourceCulture); }
        }
        
        public static string PaymentRequired {
            get { return ResourceManager.GetString("PaymentRequired", resourceCulture); }
        }
        
        public static string PaymentNotNeeded {
            get { return ResourceManager.GetString("PaymentNotNeeded", resourceCulture); }
        }
        
        public static string ReviewSubmitted {
            get { return ResourceManager.GetString("ReviewSubmitted", resourceCulture); }
        }
        
        public static string ReviewAfterCompletion {
            get { return ResourceManager.GetString("ReviewAfterCompletion", resourceCulture); }
        }
        
        public static string CompletePayment {
            get { return ResourceManager.GetString("CompletePayment", resourceCulture); }
        }
        
        public static string TotalDue {
            get { return ResourceManager.GetString("TotalDue", resourceCulture); }
        }
        
        public static string PaymentMethod {
            get { return ResourceManager.GetString("PaymentMethod", resourceCulture); }
        }
        
        public static string CreditCard {
            get { return ResourceManager.GetString("CreditCard", resourceCulture); }
        }
        
        public static string DebitCard {
            get { return ResourceManager.GetString("DebitCard", resourceCulture); }
        }
        
        public static string BankTransfer {
            get { return ResourceManager.GetString("BankTransfer", resourceCulture); }
        }
        
        public static string ConfirmPayment {
            get { return ResourceManager.GetString("ConfirmPayment", resourceCulture); }
        }
        
        public static string EditBooking {
            get { return ResourceManager.GetString("EditBooking", resourceCulture); }
        }
        
        public static string EditThisBooking {
            get { return ResourceManager.GetString("EditThisBooking", resourceCulture); }
        }
        
        public static string EditingNotAvailable {
            get { return ResourceManager.GetString("EditingNotAvailable", resourceCulture); }
        }
        
        public static string UpdateBooking {
            get { return ResourceManager.GetString("UpdateBooking", resourceCulture); }
        }
        
        public static string EditBookingDescription {
            get { return ResourceManager.GetString("EditBookingDescription", resourceCulture); }
        }
        
        public static string BackToBookingDetails {
            get { return ResourceManager.GetString("BackToBookingDetails", resourceCulture); }
        }
        
        public static string CurrentBookingInfo {
            get { return ResourceManager.GetString("CurrentBookingInfo", resourceCulture); }
        }
        
        public static string EditOnlyPendingNote {
            get { return ResourceManager.GetString("EditOnlyPendingNote", resourceCulture); }
        }

        // User/_UserBookingList
        public static string PaymentDue {
            get { return ResourceManager.GetString("PaymentDue", resourceCulture); }
        }
        
        public static string Details {
            get { return ResourceManager.GetString("Details", resourceCulture); }
        }
        
        public static string NoBookingsLabel {
            get { return ResourceManager.GetString("NoBookingsLabel", resourceCulture); }
        }
        
        public static string NoBookingsInCategory {
            get { return ResourceManager.GetString("NoBookingsInCategory", resourceCulture); }
        }
        
        public static string Paid {
            get { return ResourceManager.GetString("Paid", resourceCulture); }
        }

        // User/AddReview
        public static string AddReview {
            get { return ResourceManager.GetString("AddReview", resourceCulture); }
        }
        
        public static string UpdateReviewFor {
            get { return ResourceManager.GetString("UpdateReviewFor", resourceCulture); }
        }
        
        public static string ShareExperienceWith {
            get { return ResourceManager.GetString("ShareExperienceWith", resourceCulture); }
        }
        
        public static string BackToBooking {
            get { return ResourceManager.GetString("BackToBooking", resourceCulture); }
        }
        
        public static string ReviewSubmittedOnDate {
            get { return ResourceManager.GetString("ReviewSubmittedOnDate", resourceCulture); }
        }
        
        public static string UpdateRatingComment {
            get { return ResourceManager.GetString("UpdateRatingComment", resourceCulture); }
        }
        
        public static string WriteYourReview {
            get { return ResourceManager.GetString("WriteYourReview", resourceCulture); }
        }
        
        public static string EditYourReview {
            get { return ResourceManager.GetString("EditYourReview", resourceCulture); }
        }
        
        public static string Rating {
            get { return ResourceManager.GetString("Rating", resourceCulture); }
        }
        
        public static string SelectRating {
            get { return ResourceManager.GetString("SelectRating", resourceCulture); }
        }
        
        public static string YourReviewLabel {
            get { return ResourceManager.GetString("YourReviewLabel", resourceCulture); }
        }
        
        public static string ReviewPlaceholder {
            get { return ResourceManager.GetString("ReviewPlaceholder", resourceCulture); }
        }
        
        public static string UpdateReview {
            get { return ResourceManager.GetString("UpdateReview", resourceCulture); }
        }
        
        public static string SubmitReview {
            get { return ResourceManager.GetString("SubmitReview", resourceCulture); }
        }
        
        public static string RatingGuide {
            get { return ResourceManager.GetString("RatingGuide", resourceCulture); }
        }

        // SystemAdmin - shared table / filter labels
        public static string Page {
            get { return ResourceManager.GetString("Page", resourceCulture); }
        }

        public static string Of {
            get { return ResourceManager.GetString("Of", resourceCulture); }
        }

        public static string Showing {
            get { return ResourceManager.GetString("Showing", resourceCulture); }
        }

        public static string Filter {
            get { return ResourceManager.GetString("Filter", resourceCulture); }
        }

        public static string Clear {
            get { return ResourceManager.GetString("Clear", resourceCulture); }
        }

        public static string AllStatuses {
            get { return ResourceManager.GetString("AllStatuses", resourceCulture); }
        }

        public static string AllTenantsList {
            get { return ResourceManager.GetString("AllTenantsList", resourceCulture); }
        }

        public static string AllEntities {
            get { return ResourceManager.GetString("AllEntities", resourceCulture); }
        }

        public static string AllActions {
            get { return ResourceManager.GetString("AllActions", resourceCulture); }
        }

        public static string AllFilter {
            get { return ResourceManager.GetString("AllFilter", resourceCulture); }
        }

        public static string ActiveOnly {
            get { return ResourceManager.GetString("ActiveOnly", resourceCulture); }
        }

        public static string InactiveOnly {
            get { return ResourceManager.GetString("InactiveOnly", resourceCulture); }
        }

        public static string DeactivatedOnly {
            get { return ResourceManager.GetString("DeactivatedOnly", resourceCulture); }
        }

        public static string AvailableOnly {
            get { return ResourceManager.GetString("AvailableOnly", resourceCulture); }
        }

        public static string UnavailableOnly {
            get { return ResourceManager.GetString("UnavailableOnly", resourceCulture); }
        }

        public static string SearchLabel {
            get { return ResourceManager.GetString("SearchLabel", resourceCulture); }
        }

        public static string StatusLabel {
            get { return ResourceManager.GetString("StatusLabel", resourceCulture); }
        }

        public static string TenantLabel {
            get { return ResourceManager.GetString("TenantLabel", resourceCulture); }
        }

        public static string EntityLabel {
            get { return ResourceManager.GetString("EntityLabel", resourceCulture); }
        }

        public static string ActionLabel {
            get { return ResourceManager.GetString("ActionLabel", resourceCulture); }
        }

        public static string AvailabilityLabel {
            get { return ResourceManager.GetString("AvailabilityLabel", resourceCulture); }
        }

        public static string BackToDashboardBtn {
            get { return ResourceManager.GetString("BackToDashboardBtn", resourceCulture); }
        }

        public static string BackToUsers {
            get { return ResourceManager.GetString("BackToUsers", resourceCulture); }
        }

        // SystemAdmin - Dashboard
        public static string SystemWideOverview {
            get { return ResourceManager.GetString("SystemWideOverview", resourceCulture); }
        }

        public static string QuickActionsLabel {
            get { return ResourceManager.GetString("QuickActionsLabel", resourceCulture); }
        }

        public static string AllBookingsLink {
            get { return ResourceManager.GetString("AllBookingsLink", resourceCulture); }
        }

        public static string AllAircraftLink {
            get { return ResourceManager.GetString("AllAircraftLink", resourceCulture); }
        }

        public static string AuditLog {
            get { return ResourceManager.GetString("AuditLog", resourceCulture); }
        }

        public static string NoTenantsYetAdmin {
            get { return ResourceManager.GetString("NoTenantsYetAdmin", resourceCulture); }
        }

        public static string ViewAllBookings {
            get { return ResourceManager.GetString("ViewAllBookings", resourceCulture); }
        }

        public static string ViewAllAircraftLink {
            get { return ResourceManager.GetString("ViewAllAircraftLink", resourceCulture); }
        }

        // SystemAdmin - Tenants
        public static string ManageTenantsTitle {
            get { return ResourceManager.GetString("ManageTenantsTitle", resourceCulture); }
        }

        public static string SearchCompanyOrSlug {
            get { return ResourceManager.GetString("SearchCompanyOrSlug", resourceCulture); }
        }

        public static string NoTenantsMatchFilter {
            get { return ResourceManager.GetString("NoTenantsMatchFilter", resourceCulture); }
        }

        public static string DeactivateTenant {
            get { return ResourceManager.GetString("DeactivateTenant", resourceCulture); }
        }

        public static string ActivateTenant {
            get { return ResourceManager.GetString("ActivateTenant", resourceCulture); }
        }

        public static string ToggleTenantTitle {
            get { return ResourceManager.GetString("ToggleTenantTitle", resourceCulture); }
        }

        public static string TenantDeactivateWarning {
            get { return ResourceManager.GetString("TenantDeactivateWarning", resourceCulture); }
        }

        public static string TenantActivateInfo {
            get { return ResourceManager.GetString("TenantActivateInfo", resourceCulture); }
        }

        public static string AreYouSureWantTo {
            get { return ResourceManager.GetString("AreYouSureWantTo", resourceCulture); }
        }

        public static string ThisTenant {
            get { return ResourceManager.GetString("ThisTenant", resourceCulture); }
        }

        // SystemAdmin - Users
        public static string ManageUsersTitle {
            get { return ResourceManager.GetString("ManageUsersTitle", resourceCulture); }
        }

        public static string UsersFound {
            get { return ResourceManager.GetString("UsersFound", resourceCulture); }
        }

        public static string SearchNameOrEmail {
            get { return ResourceManager.GetString("SearchNameOrEmail", resourceCulture); }
        }

        public static string AllUsers {
            get { return ResourceManager.GetString("AllUsers", resourceCulture); }
        }

        public static string NameCol {
            get { return ResourceManager.GetString("NameCol", resourceCulture); }
        }

        public static string EmailCol {
            get { return ResourceManager.GetString("EmailCol", resourceCulture); }
        }

        public static string RolesCol {
            get { return ResourceManager.GetString("RolesCol", resourceCulture); }
        }

        public static string Registered {
            get { return ResourceManager.GetString("Registered", resourceCulture); }
        }

        public static string BookingsCol {
            get { return ResourceManager.GetString("BookingsCol", resourceCulture); }
        }

        public static string Deactivated {
            get { return ResourceManager.GetString("Deactivated", resourceCulture); }
        }

        public static string NoUsersMatchFilter {
            get { return ResourceManager.GetString("NoUsersMatchFilter", resourceCulture); }
        }

        public static string ReactivateUser {
            get { return ResourceManager.GetString("ReactivateUser", resourceCulture); }
        }

        public static string DeactivateUser {
            get { return ResourceManager.GetString("DeactivateUser", resourceCulture); }
        }

        public static string AreYouSureReactivate {
            get { return ResourceManager.GetString("AreYouSureReactivate", resourceCulture); }
        }

        public static string AreYouSureDeactivate {
            get { return ResourceManager.GetString("AreYouSureDeactivate", resourceCulture); }
        }

        public static string ReactivateInfo {
            get { return ResourceManager.GetString("ReactivateInfo", resourceCulture); }
        }

        public static string DeactivateUserWarning {
            get { return ResourceManager.GetString("DeactivateUserWarning", resourceCulture); }
        }

        // SystemAdmin - All Aircraft
        public static string AllAircraftTitle {
            get { return ResourceManager.GetString("AllAircraftTitle", resourceCulture); }
        }

        public static string AllAircraftHeading {
            get { return ResourceManager.GetString("AllAircraftHeading", resourceCulture); }
        }

        public static string AircraftFoundAcrossTenants {
            get { return ResourceManager.GetString("AircraftFoundAcrossTenants", resourceCulture); }
        }

        public static string SearchRegistrationMakeModelTenant {
            get { return ResourceManager.GetString("SearchRegistrationMakeModelTenant", resourceCulture); }
        }

        public static string RegistrationCol {
            get { return ResourceManager.GetString("RegistrationCol", resourceCulture); }
        }

        public static string MakeAndModel {
            get { return ResourceManager.GetString("MakeAndModel", resourceCulture); }
        }

        public static string YearCol {
            get { return ResourceManager.GetString("YearCol", resourceCulture); }
        }

        public static string HourlyRateCol {
            get { return ResourceManager.GetString("HourlyRateCol", resourceCulture); }
        }

        public static string BaseAirportCol {
            get { return ResourceManager.GetString("BaseAirportCol", resourceCulture); }
        }

        public static string NoAircraftMatchFilter {
            get { return ResourceManager.GetString("NoAircraftMatchFilter", resourceCulture); }
        }

        // SystemAdmin - All Bookings
        public static string AllBookingsTitle {
            get { return ResourceManager.GetString("AllBookingsTitle", resourceCulture); }
        }

        public static string AllBookingsHeading {
            get { return ResourceManager.GetString("AllBookingsHeading", resourceCulture); }
        }

        public static string BookingsFoundAcrossTenants {
            get { return ResourceManager.GetString("BookingsFoundAcrossTenants", resourceCulture); }
        }

        public static string SearchPilotAircraftTenant {
            get { return ResourceManager.GetString("SearchPilotAircraftTenant", resourceCulture); }
        }

        public static string PilotCol {
            get { return ResourceManager.GetString("PilotCol", resourceCulture); }
        }

        public static string StartCol {
            get { return ResourceManager.GetString("StartCol", resourceCulture); }
        }

        public static string EndCol {
            get { return ResourceManager.GetString("EndCol", resourceCulture); }
        }

        public static string AmountCol {
            get { return ResourceManager.GetString("AmountCol", resourceCulture); }
        }

        public static string CreatedCol {
            get { return ResourceManager.GetString("CreatedCol", resourceCulture); }
        }

        public static string NoBookingsMatchFilter {
            get { return ResourceManager.GetString("NoBookingsMatchFilter", resourceCulture); }
        }

        // SystemAdmin - Audit Log
        public static string AuditLogTitle {
            get { return ResourceManager.GetString("AuditLogTitle", resourceCulture); }
        }

        public static string TotalEntries {
            get { return ResourceManager.GetString("TotalEntries", resourceCulture); }
        }

        public static string SearchDetailsEmailIp {
            get { return ResourceManager.GetString("SearchDetailsEmailIp", resourceCulture); }
        }

        public static string LogEntries {
            get { return ResourceManager.GetString("LogEntries", resourceCulture); }
        }

        public static string TimestampCol {
            get { return ResourceManager.GetString("TimestampCol", resourceCulture); }
        }

        public static string TenantIdCol {
            get { return ResourceManager.GetString("TenantIdCol", resourceCulture); }
        }

        public static string UserCol {
            get { return ResourceManager.GetString("UserCol", resourceCulture); }
        }

        public static string IpCol {
            get { return ResourceManager.GetString("IpCol", resourceCulture); }
        }

        public static string DetailsCol {
            get { return ResourceManager.GetString("DetailsCol", resourceCulture); }
        }

        public static string NoAuditLogMatch {
            get { return ResourceManager.GetString("NoAuditLogMatch", resourceCulture); }
        }

        // SystemAdmin - Edit User Roles
        public static string EditRolesTitle {
            get { return ResourceManager.GetString("EditRolesTitle", resourceCulture); }
        }

        public static string AspNetIdentityRoles {
            get { return ResourceManager.GetString("AspNetIdentityRoles", resourceCulture); }
        }

        public static string NoRolesDefined {
            get { return ResourceManager.GetString("NoRolesDefined", resourceCulture); }
        }

        public static string CurrentlyAssigned {
            get { return ResourceManager.GetString("CurrentlyAssigned", resourceCulture); }
        }

        public static string SaveRoles {
            get { return ResourceManager.GetString("SaveRoles", resourceCulture); }
        }

        public static string CompanyMemberships {
            get { return ResourceManager.GetString("CompanyMemberships", resourceCulture); }
        }

        public static string NoCompanyMemberships {
            get { return ResourceManager.GetString("NoCompanyMemberships", resourceCulture); }
        }
    }
}
