apiVersion: v1
kind: Secret
metadata: { name: fleet-secret, namespace: ns-fleet }
type: Opaque
stringData:
  ConnectionStrings__FleetConnection: "Host=postgres.ns-infra.svc.cluster.local;Port=5432;Database=aircraft-fleet;Username=postgres;Password=postgres"
  JWT__Key:           "some_secret_password_dont_share.at.iausdhviushviusdhuisdhgiusdfhliuhdiufvhidufvhidufhviudsfh"
  RabbitMQ__UserName: "guest"
  RabbitMQ__Password: "guest"
