# Patches default ServiceAccounts to automatically use the local-registry imagePullSecret for pulling images from the private in-cluster registry.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ns-users
imagePullSecrets:
  - name: local-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ns-fleet
imagePullSecrets:
  - name: local-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ns-booking
imagePullSecrets:
  - name: local-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: ns-frontend
imagePullSecrets:
  - name: local-registry
