<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Allow Infrastructure to register internal service implementations -->
  <ItemGroup>
    <InternalsVisibleTo Include="Users.Infrastructure" />
    <InternalsVisibleTo Include="Users.Tests" />
    <InternalsVisibleTo Include="Integration.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Users.Domain\Users.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

</Project>
