apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
  namespace: ns-frontend
spec:
  template:
    spec:
      serviceAccountName: vue-frontend-runtime
      automountServiceAccountToken: false
